---
title: "01_PlotPCA"
author: "Jun"
date: "4/22/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(hrbrthemes)
library(readr)
library(tidyverse)
library(ggfortify)
library(FactoMineR)
library(factoextra)
library(corrplot)
library(ggpubr)
library(sf)
library(dplyr)
```


```{r}
metaTable <- read_csv('C:/Users/yangj/Box/phd/Dave Lab/R/MB599/BL Project/03 PCA/00_14LC.csv')

dMeta <- metaTable[-1]

meta_PCA <- PCA(dMeta, graph = FALSE)

```

```{r}
eig.val <- get_eigenvalue(meta_PCA) 

eigPlot<-fviz_eig(meta_PCA, addlabels = TRUE, ylim = c(0, 70))

```

```{r}
var <- get_pca_var(meta_PCA)

head(var$coord, 4)

corrplot(var$cos2, is.corr=FALSE)
```

```{r}
fviz_pca_ind(meta_PCA, pointsize = "cos2", 
             pointshape = 21, fill = "#E7B800",
             repel = TRUE # Avoid text overlapping (slow if many points)
             )
```

```{r}
cosPlot<- fviz_cos2(meta_PCA, choice = "var", axes = 1:2)
cosPlot
```

```{r}
# Contributions of variables to PC1
DimPlot1<- fviz_contrib(meta_PCA, choice = "var", axes = 1, top = 40)
DimPlot1
# Contributions of variables to PC2
DimPlot2<- fviz_contrib(meta_PCA, choice = "var", axes = 2, top = 40)
DimPlot2
```

```{r}
conPlot<-fviz_contrib(meta_PCA, choice = "ind", axes = 1:5)
conPlot
```

```{r}
IndPlot <- fviz_pca_biplot(meta_PCA, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
IndPlot
```


```{r}
PCAPlot12 <- fviz_pca_ind(meta_PCA, axes = c(1,2),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot13 <- fviz_pca_ind(meta_PCA, axes = c(1,3),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot14 <- fviz_pca_ind(meta_PCA, axes = c(1,4),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot15 <- fviz_pca_ind(meta_PCA, axes = c(1,5),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot23 <- fviz_pca_ind(meta_PCA, axes = c(2,3),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot24 <- fviz_pca_ind(meta_PCA, axes = c(2,4),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot25 <- fviz_pca_ind(meta_PCA, axes = c(2,5),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot34 <- fviz_pca_ind(meta_PCA, axes = c(3,4),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot35 <- fviz_pca_ind(meta_PCA, axes = c(3,5),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot45 <- fviz_pca_ind(meta_PCA, axes = c(4,5),
             geom.ind = "point", # show points only (nbut not "text")
             col.ind = metaTable$sample, # color by groups
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "convex",
             legend.title = "Samples"
             ) 
PCAPlot12
PCAPlot13
PCAPlot14
PCAPlot15
PCAPlot23
PCAPlot24
PCAPlot25
PCAPlot34
PCAPlot35
PCAPlot45
```

```{r}
ggexport(plotlist = list(eigPlot, cosPlot, DimPlot1, DimPlot2, conPlot, IndPlot, PCAPlot15), 
         filename = "03_14LCPCA.pdf", width = 8, height = 6)
```