---
title: "05_pheatmap_Meta"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load package
library(pheatmap)
library(readr)
library(tidyverse)
library(ggpubr)
library(hrbrthemes)
library(dendextend)
```

```{r}
metaTable_test <- read_csv('C:/Users/yangj/Box/phd/Dave Lab/R/MB599/BL Project/01 Clean Data and Data Normalizating/00_10LC.csv')
metaTable_test <- column_to_rownames(metaTable_test,var="sample")

metaTable_test <- mutate_all(metaTable_test, function(x) as.numeric(as.character(x)))

metaTable_test2 <- as.matrix.data.frame(metaTable_test)

my_hclust_gene <- hclust(dist(metaTable_test2), method = "complete")
my_gene_col <- cutree(tree = as.dendrogram(my_hclust_gene), k = 3)

my_gene_col <- data.frame(cluster = ifelse(test = my_gene_col == 1, yes = "cluster 1", no = ifelse(test = my_gene_col == 2, yes = "cluster 2", no = "cluster 3")))

breaksList = seq(0, 1, by = 0.1)

P <- pheatmap(metaTable_test2)
Q <- pheatmap(metaTable_test2, color = colorRampPalette(c("blue", "white",  "red"))(length(breaksList)), breaks = breaksList, annotation_row = my_gene_col, cellwidth = 10, cellheight = 10)
Q
```

```{r}
ggexport(plotlist = list(Q), 
         filename = "05_03_10LC_all_Heatmap.pdf", width = 8, height = 100)
```


```{r}
metaTable_test <- read_csv('C:/Users/yangj/Box/phd/Dave Lab/R/MB599/BL Project/01 Clean Data and Data Normalizating/00_14LC.csv')
metaTable_test <- column_to_rownames(metaTable_test,var="sample")

metaTable_test <- mutate_all(metaTable_test, function(x) as.numeric(as.character(x)))

metaTable_test2 <- as.matrix.data.frame(metaTable_test)

my_hclust_gene <- hclust(dist(metaTable_test2), method = "complete")
my_gene_col <- cutree(tree = as.dendrogram(my_hclust_gene), k = 3)

my_gene_col <- data.frame(cluster = ifelse(test = my_gene_col == 1, yes = "cluster 1", no = ifelse(test = my_gene_col == 2, yes = "cluster 2", no = "cluster 3")))

breaksList = seq(0, 1, by = 0.1)

P <- pheatmap(metaTable_test2)
Q <- pheatmap(metaTable_test2, color = colorRampPalette(c("blue", "white",  "red"))(length(breaksList)), breaks = breaksList, annotation_row = my_gene_col, cellwidth = 10, cellheight = 10)
Q
```

```{r}
ggexport(plotlist = list(Q), 
         filename = "05_03_14LC_all_Heatmap.pdf", width = 8, height = 100)
```